### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by iamharshkumar97** [jparise/stale#10]
I have downloaded the files on my Windows 10 laptop. Unzipped them and have run the stale.py program by entering -t argument.

I am getting HTTP Error 401: Unauthorized error

I am on Python3

**Comment by jparise** [comment]
Is there any additional output if you also include the `-v` (verbose) flag?

And you're definitely passing your Pinboard API token (from https://pinboard.in/settings/password) and not your account password, right?
