### ISSUE TITLE
Got Certificate error when trying to execute script

### ISSUE THREAD

**Issue by cyberchucktx** [jparise/stale#8]
I just downloaded the script and received the following error: 

> bash-3.2$ python3 stale.py -t '<my-pinboard-api-key>' -v
Failed to retrieve posts: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>

Running this on MacOSX (latest version), python3.7.

**Comment by cyberchucktx** [comment]
Partial answer: must install certificates for Python under OSX (see https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org ) for details.

**Comment by jparise** [comment]
Does this only happen for a few specific hosts? I haven't been able to reproduce this myself.

**Comment by jparise** [comment]
I was able to narrow this down. It only happens for a few hosts with newer certificate authorities. I've updated the `README.md` to mention this.
